<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $flashcard->title }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #6366f1;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .title {
            font-size: 24px;
            color: #4f46e5;
            margin: 0;
        }
        .description {
            font-style: italic;
            color: #666;
            margin-top: 10px;
        }
        .section-title {
            font-size: 18px;
            color: #1f2937;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 5px;
            margin-top: 30px;
            margin-bottom: 15px;
        }
        .summary-box {
            background-color: #f3f4f6;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }
        .flashcard {
            margin-bottom: 20px;
            page-break-inside: avoid;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 15px;
        }
        .question {
            font-weight: bold;
            color: #4f46e5;
            margin-bottom: 5px;
        }
        .answer {
            color: #374151;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 10px;
            color: #9ca3af;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">{{ $flashcard->title }}</h1>
        @if($flashcard->description)
            <p class="description">{{ $flashcard->description }}</p>
        @endif
    </div>

    @if($flashcard->summary)
        <div class="section-title">Executive Summary</div>
        <div class="summary-box">
            {!! nl2br(e($flashcard->summary)) !!}
        </div>
    @endif

    <div class="section-title">Flashcards ({{ count($flashcard->cards) }})</div>
    
    @foreach($flashcard->cards as $index => $card)
        <div class="flashcard">
            <div class="question">Q{{ $index + 1 }}: {{ $card['question'] }}</div>
            <div class="answer">A: {{ $card['answer'] }}</div>
        </div>
    @endforeach

    <div class="footer">
        Generated by Flashcard AI on {{ now()->format('Y-m-d H:i') }}
    </div>
</body>
</html>
